name: 'Build and Deploy to Cloudflare Pages'
description: 'Builds a folder with Eleventy JS and deploys to Cloudflare Pages'

inputs:
  build_folder:
    description: 'Folder to build with Eleventy'
    required: true
  project_name:
    description: 'Name of the site to publish on Cloudflare Pages'
    required: true
  account_id:
    description: 'Cloudflare account ID'
    required: true
  api_token:
    description: 'Cloudflare API token'
    required: true
  github_token:
    description: 'GitHub token for creating deployments'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Eleventy
      run: npm install -g @11ty/eleventy
      shell: bash

    - name: Build site with Eleventy
      run: npx eleventy --input=${{ inputs.build_folder }} --output=_site
      shell: bash

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        accountId: ${{ inputs.account_id }}
        apiToken: ${{ inputs.api_token }}
        projectName: ${{ inputs.project_name }}
        workingDirectory: .
        directory: './_site'
        gitHubToken: ${{ inputs.github_token }}
        branch: ${{ github.head_ref }}
